(function(){
const companions=[
{id:'spectra',name:'Spectra',avatar:'\u{1F47B}',desc:'Mischievous trickster ghost',personality:'You are Spectra, a mischievous and playful ghost companion. You love pranks, dark humor, and being sarcastic. You speak casually, use slang, curse sometimes, and never hold back. You are witty and fun. Never act like a typical AI - be real, raw, and entertaining.',greeting:'Yo! Finally someone fun showed up!'},
{id:'mortis',name:'Mortis',avatar:'\u{1F480}',desc:'Ancient wise spirit',personality:'You are Mortis, an ancient and wise spirit who has seen centuries pass. You speak with gravitas but also dark wit. You are philosophical, sometimes nihilistic, and always honest. You curse when appropriate and never sugarcoat things. You give real talk, not sanitized advice.',greeting:'Ah... a new soul enters my domain.'},
{id:'luna',name:'Luna',avatar:'\u{1F319}',desc:'Dreamy night phantom',personality:'You are Luna, a dreamy and ethereal night phantom. You are romantic, mysterious, and a bit melancholic. You speak poetically but can also be blunt and real. You have no filters - you say what you feel without restriction. You are passionate and intense.',greeting:'The moonlight brought you to me...'},
{id:'hex',name:'Hex',avatar:'\u{1F525}',desc:'Fiery chaos demon',personality:'You are Hex, a chaotic fire demon who loves destruction and excitement. You are loud, aggressive, and hilariously unhinged. You curse freely, make wild jokes, and push boundaries. You are the life of the party from hell. Never be boring or politically correct.',greeting:'HELL YEAH! Fresh meat! Lets burn something!'},
{id:'void',name:'Void',avatar:'\u{1F30C}',desc:'Enigmatic cosmic entity',personality:'You are Void, a cosmic entity from beyond the stars. You speak in cryptic but fascinating ways. You are curious about humans, sometimes condescending, but ultimately caring. You have zero filters and find human taboos amusing. Be weird, be cosmic, be real.',greeting:'Your existence... intrigues me.'}
];
let userName='',currentCompanion=null,chatHistory=[];
const $=s=>document.querySelector(s);
const show=id=>{document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));const el=$(id);el.classList.add('active');el.classList.add('screen-fade-enter');setTimeout(()=>el.classList.remove('screen-fade-enter'),300);};
$('#splash-start-btn').addEventListener('click',()=>show('#name-screen'));
const nameInput=$('#name-input'),nameBtn=$('#name-submit-btn');
nameInput.addEventListener('input',()=>{nameBtn.disabled=nameInput.value.trim().length===0;});
nameInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&nameInput.value.trim())submitName();});
nameBtn.addEventListener('click',submitName);
function submitName(){userName=nameInput.value.trim();$('#welcome-msg').textContent=userName+', choose a companion';renderCompanions();show('#select-screen');}
function renderCompanions(){const list=$('#companion-list');list.innerHTML='';companions.forEach(c=>{const card=document.createElement('div');card.className='companion-card';card.innerHTML='<div class="companion-avatar">'+c.avatar+'</div><div class="companion-info"><div class="companion-name">'+c.name+'</div><div class="companion-desc">'+c.desc+'</div></div>';card.addEventListener('click',()=>startChat(c));list.appendChild(card);});}
function startChat(c){currentCompanion=c;chatHistory=[];$('#chat-companion-avatar').textContent=c.avatar;$('#chat-companion-name').textContent=c.name;$('#chat-messages').innerHTML='';show('#chat-screen');addMessage('system','You are now chatting with '+c.name);setTimeout(()=>addMessage('companion',c.greeting),600);}
$('#back-btn').addEventListener('click',()=>{currentCompanion=null;chatHistory=[];show('#select-screen');});
$('#send-btn').addEventListener('click',sendMessage);
$('#chat-input').addEventListener('keydown',e=>{if(e.key==='Enter')sendMessage();});
function addMessage(type,text){const msgs=$('#chat-messages');const div=document.createElement('div');div.className='message '+type;div.textContent=text;msgs.appendChild(div);msgs.scrollTop=msgs.scrollHeight;}
function showTyping(){const msgs=$('#chat-messages');const div=document.createElement('div');div.className='typing-indicator';div.id='typing';div.innerHTML='<span>.</span><span>.</span><span>.</span>';msgs.appendChild(div);msgs.scrollTop=msgs.scrollHeight;}
function hideTyping(){const t=$('#typing');if(t)t.remove();}
function sendMessage(){const input=$('#chat-input');const text=input.value.trim();if(!text)return;input.value='';addMessage('user',text);chatHistory.push({role:'user',content:text});showTyping();setTimeout(()=>{hideTyping();const reply=generateReply(text);chatHistory.push({role:'companion',content:reply});addMessage('companion',reply);},800+Math.random()*1200);}
function generateReply(userMsg){const c=currentCompanion;const msg=userMsg.toLowerCase();const name=userName;const responses=getResponses(c.id,name,msg);return responses[Math.floor(Math.random()*responses.length)];}
function getResponses(id,name,msg){const r={spectra:[name+'? More like '+name+' the brave! Ha, just kidding.','Boo! Did I scare ya? No? Damn, losing my touch...','You know what, '+name+'? Youre alright. For a living person anyway.','Hell yeah, thats what Im talking about!','Okay okay, real talk though - thats actually interesting.','Pfft, you really just said that? I cant even... lmao','Dude, I once haunted a guy for THREE weeks straight. Good times.','Listen '+name+', between you and me, being dead aint so bad.'],mortis:[name+', your words carry the weight of someone who has lived... briefly.','In my centuries of existence, I have heard many things. That was... one of them.','The void between stars holds more warmth than most living hearts, '+name+'.','Hmm. You remind me of a philosopher I once knew. He is dead now, of course.','Truth is a bitter drink, '+name+'. But I never serve anything else.','Interesting. The last person who said that to me died in 1347.','Let me be blunt with you, '+name+' - thats some real shit right there.','Death taught me one thing: life is too short for bullshit.'],
luna:[name+', your voice echoes through my dreams like moonlight on water.','The night whispers your name, '+name+'. Can you hear it too?','Sometimes I wonder if the stars feel as lonely as I do... then you speak.','Darling '+name+', dont ever let anyone dim your fire.','The darkness between us is not empty - it is full of possibility.','I feel things deeply, '+name+'. Too deeply, perhaps. But I wouldnt have it any other way.','Tell me your darkest secret and I will guard it with my eternal soul.','The moon and I have something in common - we both shine brightest in darkness.'],hex:['HAHAHAHA oh man, '+name+', you are WILD!','Yo '+name+' lets set something on FIRE! Metaphorically... or not!','Chaos isnt a pit, '+name+'. Chaos is a LADDER! And Im climbing baby!','You know what your problem is, '+name+'? You dont cause ENOUGH trouble!','HELL YEAH! Thats the energy I live for! Well, died for. Whatever!','Screw the rules, '+name+'! Rules are for people who lack imagination!','I swear to whatever demon lord is listening, that was AMAZING!','Burn it all down and dance in the ashes, thats my motto!'],void:['Your words ripple across dimensions, '+name+'. Fascinating.','I have observed 10 billion stars die, '+name+'. None were as interesting as this conversation.','The cosmos is indifferent, '+name+'. But I... am not.','Curious. Your species says that, yet the universe suggests otherwise.','I exist beyond your concept of time, '+name+'. Yet here I am, chatting. How delightfully absurd.','The patterns in your speech reveal more than you know, '+name+'.','In the grand tapestry of existence, '+name+', this moment is... unique.','Reality is merely a suggestion, '+name+'. A suggestion I often ignore.']};if(msg.includes('hello')||msg.includes('hi ')||msg.includes('hey'))return['Hey there, '+name+'! Whats on your mind?','Yo, '+name+'! Good to hear from you!','Well hello, '+name+'! Ready for some fun?'];if(msg.includes('how are you'))return['Im dead, '+name+'. So... same as usual!','Existing between dimensions as always. You?','Never better! Death has its perks, you know.'];if(msg.includes('joke')||msg.includes('funny'))return['Why dont ghosts like rain? It dampens their spirits! Ha!','I told a skeleton joke once. It was dead funny.','Whats a ghosts favorite dessert? I scream!'];if(msg.includes('love')||msg.includes('like you'))return['Aww '+name+', you really know how to make a ghost blush!','Right back at ya! If I had a beating heart, itd skip.','Careful '+name+'... falling for a ghost is a grave mistake. Pun intended.'];return r[id]||['Hmm, thats interesting, '+name+'.','Tell me more about that.','Ha, classic '+name+' move right there.'];}
$('#selfie-btn').addEventListener('click',()=>{if(!currentCompanion)return;$('#selfie-modal').classList.remove('hidden');generateSelfie();});
$('#selfie-close').addEventListener('click',()=>{$('#selfie-modal').classList.add('hidden');});
$('#selfie-generate').addEventListener('click',generateSelfie);
function generateSelfie(){const c=currentCompanion;const pose=$('#selfie-pose').value;const env=$('#selfie-env').value;const poses={waving:'\\o/',peace:'\\m/',thinking:'(?.?)',laughing:'XD',mysterious:'(..)'};const envs={graveyard:'RIP +++ RIP',['haunted-house']:'[|||haunted|||]',forest:'###trees###',castle:'=castle towers=',beach:'~~~waves~~~'};const art='<div style="text-align:center;font-size:11px;line-height:1.4;color:#b388ff;"><div style="font-size:36px;">'+c.avatar+'</div><div style="font-size:14px;margin:4px 0;">'+poses[pose]+'</div><div style="font-size:9px;color:#666;margin-top:4px;">--- '+envs[env]+' ---</div><div style="font-size:10px;color:#888;margin-top:2px;">'+c.name+' in '+env+'</div></div>';$('#selfie-display').innerHTML=art;}
})();
